config/routes.rb
Rails.application.routes.draw do

  resources :budgets do  
    collection { post :import }
    get 'createbudget' => 'budgets#create'
    get 'budgets' => 'budgets#index'
  end  

resources :users, only: [:update, :destroy]

get 'users', to: 'users#new'
get 'users/index', to: 'users#index'

get 'users/new', to: 'users#new', as: 'new_user'
get 'users/:id/new', to: 'users#new'
get 'users/:id/edit', to: 'users#edit', as: 'edit_user'
get 'users/:id', to: 'users#share'
post 'users/:id', to: 'users#update'
patch 'users/:id', to: 'users#update'
patch 'users/:id/update', to: 'users#update'
patch 'users/:id/new', to: 'users#update'
put 'users/:id', to: 'users#update'
delete 'users/:id', to: 'users#destroy'
delete 'users/:id/new', to: 'users#destroy'
get 'users/:id/ndfl', to: 'users#ndfl', as: 'ndfl_user'
get 'users/:id/showtaxes', to: 'users#showtaxes', as: 'showtaxes_user'
get 'users/:id/showspending', to: 'users#showspending', as: 'showspending_user'
get 'users/:id/askquestions', to: 'users#askquestions', as: 'askquestions_user'
get 'users/:id/anotheruser', to: 'users#anotheruser', as: 'anotheruser_user'
get 'users/:id/share' => 'users#share', as: 'share_user'
get 'treatments' => 'treatmentby_regions#index'
post 'users', to: 'users#create', as: 'user_create'
  

root 'users#root'

end

app/models/user.rb
class User < ActiveRecord::Base

attr_accessor :consent

  validates :consent, acceptance: {message: "Для продолжения необходимо согласие" }, on: :create
  validates :aftertaxwage, presence: {message: "Укажите значение" }, on: :create
  validates :taxest, presence: {message: "Укажите значение" }, on: :create
  validates :taxcertainty, presence: {message: "Укажите значение" }, on: :create
  validates :educ, presence: {message: "Выберите из списка" }, on: :create
  validates :educ, numericality: true, on: :create
  validates :residence, presence: {message: "Выберите из списка" }, on: :create
  validates :residence, numericality: true, on: :create
  validates :occup, presence: {message: "Выберите из списка" }, on: :create
  validates :occup, numericality: true, on: :create
  validates :elec_presid, presence: {message: "Выберите из списка" }, on: :create
  validates :elec_presid, numericality: true, on: :create
  validates :age, presence: {message: "Укажите значение"}, on: :create
  validates :age, inclusion: {in: 14..99, message: "Возраст не может быть меньше 14 лет" }, on: :create
  validates :sex, presence: {message: "Выберите значение"}, on: :create
  
  validates :treattax, presence: {message: "Укажите значение" }, on: :update
  validates :treatapprove, presence: {message: "Укажите значение" }, on: :update
  validates :petit_spending, presence: {message: "Укажите значение" }, on: :update
  validates :petit_account, presence: {message: "Укажите значение" }, on: :update


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :share]
  http_basic_authenticate_with name: "misha", password: "lapochka", only: [:index, :show, :edit, :destroy]


  def index
    @users = User.order(:id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    
    if cookies[:user_created_id] != nil
      puts "user_created_id" + cookies[:user_created_id].to_s
      if (User.exists?(cookies[:user_created_id])) then
        @user = User.find(cookies[:user_created_id])
        render :share
      else
        @user = User.new(consent: cookies[:user_consent], aftertaxwage: cookies[:user_aftertaxwage], wagerange: cookies[:user_wagerange], age: cookies[:user_age], sex: cookies[:user_sex], residence: cookies[:user_residence], educ: cookies[:user_educ], uni: cookies[:user_uni], uniother: cookies[:user_uniother], statefin: cookies[:user_statefin], residence: cookies[:user_residence], occup: cookies[:user_occup], elec_presid: cookies[:user_elec_presid], taxest: cookies[:user_taxest], taxcertainty: cookies[:user_taxcertainty], media: cookies[:user_media], media1: cookies[:user_media1], media2: cookies[:user_media2], media3: cookies[:user_media3], media4: cookies[:user_media4], media5: cookies[:user_media5], media6: cookies[:user_media6], media7: cookies[:user_media7], media8: cookies[:user_media8], media9: cookies[:user_media9])
      end
    else
      @user = User.new(consent: cookies[:user_consent], aftertaxwage: cookies[:user_aftertaxwage], wagerange: cookies[:user_wagerange], age: cookies[:user_age], sex: cookies[:user_sex], residence: cookies[:user_residence], educ: cookies[:user_educ], uni: cookies[:user_uni], uniother: cookies[:user_uniother], statefin: cookies[:user_statefin], residence: cookies[:user_residence], occup: cookies[:user_occup], elec_presid: cookies[:user_elec_presid], taxest: cookies[:user_taxest], taxcertainty: cookies[:user_taxcertainty], media: cookies[:user_media], media1: cookies[:user_media1], media2: cookies[:user_media2], media3: cookies[:user_media3], media4: cookies[:user_media4], media5: cookies[:user_media5], media6: cookies[:user_media6], media7: cookies[:user_media7], media8: cookies[:user_media8], media9: cookies[:user_media9])
      puts "New user"
    end
    
  end

  # GET /users/1/edit
  def edit
  end
  
  def showtaxes
    @user = User.find(params[:id])
  end
  
  
  def anotheruser
    @user = User.new(aftertaxwage:0, wagerange:0, ref:cookies[:user_created_id])
    cookies.permanent[:user_ref] = cookies[:user_created_id]
    cookies.delete :user_created_id
    render :new
  end
  
  def showspending
    @budgets = Budget.all
    @user = User.find(params[:id])
    @titles = Budget.find_by code: '0'
    @federal = Budget.find_by code: '-1'
    @pfr = Budget.find_by code: '-2'
    @fss = Budget.find_by code: '-3'
    @foms = Budget.find_by code: '-4'
    
    @region = Budget.find_by code: @user.residence
    if @region == nil
      @region = Budget.find_by code: '77'
    end
    
  end
  
  def askquestions
    @user = User.find(params[:id])
  end
  
  def share
    @user = User.find(params[:id])
  end
  def ndfl
    
    @user = User.find(params[:id])
    
  end
  
  def root
    if params[:campaign] != nil
      cookies.permanent[:user_campaign] = params[:campaign] 
      puts "Cookies << campaign = " + params[:campaign].to_s
    end
    if params[:source] != nil
      cookies.permanent[:user_source] = params[:source] 
      puts "Cookies << source = " + params[:source].to_s
    end
    cookies.permanent[:user_httpref] = request.env['HTTP_REFERER']
    puts "Cookies << httpref = " + request.env['HTTP_REFERER'].to_s
    cookies.permanent[:user_ipaddress] = request.remote_ip
    puts "Cookies << ipaddress = " + request.remote_ip.to_s
    redirect_to action: 'new'
  end

  # POST /users
  # POST /users.json
  def create
    
    cookies.permanent[:user_consent] = user_params[:consent] if user_params[:consent] != nil
    cookies.permanent[:user_aftertaxwage] = user_params[:aftertaxwage] if user_params[:aftertaxwage] != nil
    cookies.permanent[:user_wagerange] = user_params[:wagerange] if user_params[:wagerange] != nil
    cookies.permanent[:user_age] = user_params[:age] if user_params[:age] != nil
    cookies.permanent[:user_sex] = user_params[:sex] if user_params[:sex] != nil
    cookies.permanent[:user_educ] = user_params[:educ] if user_params[:educ] != nil
    cookies.permanent[:user_uni] = user_params[:uni] if user_params[:uni] != nil
    cookies.permanent[:user_uniother] = user_params[:uniother] if user_params[:uniother] != nil
    cookies.permanent[:user_occup] = user_params[:occup] if user_params[:occup] != nil
    cookies.permanent[:user_residence] = user_params[:residence] if user_params[:residence] != nil
    cookies.permanent[:user_elec_presid] = user_params[:elec_presid] if user_params[:elec_presid] != nil
    cookies.permanent[:user_taxest] = user_params[:taxest] if user_params[:taxest] != nil
    cookies.permanent[:user_taxcertainty] = user_params[:taxcertainty] if user_params[:taxcertainty] != nil
    cookies.permanent[:user_media] = user_params[:media] if user_params[:media] != nil
    cookies.permanent[:user_media1] = user_params[:media1] if user_params[:media1] != nil
    cookies.permanent[:user_media2] = user_params[:media2] if user_params[:media2] != nil
    cookies.permanent[:user_media3] = user_params[:media3] if user_params[:media3] != nil
    cookies.permanent[:user_media4] = user_params[:media4] if user_params[:media4] != nil
    cookies.permanent[:user_media5] = user_params[:media5] if user_params[:media5] != nil
    cookies.permanent[:user_media6] = user_params[:media6] if user_params[:media6] != nil
    cookies.permanent[:user_media7] = user_params[:media7] if user_params[:media7] != nil
    cookies.permanent[:user_media8] = user_params[:media8] if user_params[:media8] != nil
    cookies.permanent[:user_media9] = user_params[:media9] if user_params[:media9] != nil
    cookies.permanent[:user_media10] = user_params[:media10] if user_params[:media10] != nil
    cookies.permanent[:user_statefin] = user_params[:statefin] if user_params[:statefin] != nil
    cookies.permanent[:user_media_other] = user_params[:media_other] if user_params[:media_other] != nil
    
    @user = User.new(user_params)        
    respond_to do |format|
      if @user.save
        puts "saved user"
        if @user.wagerange.nil?
          @user.update_column(:wagerange, 0)
          puts "set wagerange to 0"
        end  
        cookies.permanent[:user_created_id] = @user.id
        pretax =  @user.aftertaxwage.to_i/0.87
        puts pretax
        limit14 = 624000 
        @user.update_column(:paid_ndfl, pretax * 12 * 0.13)
        
        @user.update_column(:paid_pfr, [pretax*12, limit14].min * 0.22 + [pretax*12 - limit14, 0].max *  0.1)
        
        @user.update_column(:paid_fss, [pretax*12, limit14].min*0.029)
        
        @user.update_column(:paid_foms, [pretax*12, limit14].min*0.051)
        
        @user.update_column(:paid_other, pretax*12*0.241220)
        
        @user.update_column(:useragent, request.env['HTTP_USER_AGENT'])
        
        @user.update_column(:httpref, cookies[:user_httpref]) if !cookies[:user_httpref].nil?
        
        @user.update_column(:ipaddress, cookies[:user_ipaddress]) if !cookies[:user_ipaddress].nil?
        
        @user.update_column(:ref, cookies[:user_ref]) if !cookies[:user_ref].nil?
        
        @user.update_column(:source, cookies[:user_source]) if !cookies[:user_source].nil?
        
        @user.update_column(:campaign, cookies[:user_campaign]) if !cookies[:user_campaign].nil?
        
        
#РАНДОМИЗАЦИЯ
        
        puts 'calc treatment'
        TreatmentByCampaign.all.each do |t|
          puts "campaign = " + t.title.to_s + " treatindex = " + t.index.to_s
        end
        @tc = TreatmentByCampaign.find_by title:@user.campaign
        if (@tc.nil? )
          #Название кампании не найдено
          @tc = TreatmentByCampaign.new(title:@user.campaign, index:-1)
        end
        @treat = @tc.index
        if (@treat == -1)
          @user.update_column(:treatment, rand(2))
          @tc.index = @user.treatment
          @tc.save
          # 1 - показываем вопросы до showtaxes, 0 - после showtaxes          
        else
          @user.update_column(:treatment, 1 - @treat)
          @tc.index = -1
          @tc.save
        end
          
=begin        
        @treatreg = TreatmentbyRegion.find(@user.residence)
        @treat = @treatreg.byeduc[@user.educ].to_i
        puts 'treat vector old ' + @treatreg.byeduc.to_s
        puts 'educ index ' + @user.educ.to_s
        if (@treat == -1)
          @user.update_column(:treatment, rand(2))
          @treatreg.byeduc[@user.educ] = @user.treatment
          @treatreg.save
          
# 1 - показываем вопросы до showtaxes, 0 - после showtaxes          
        else
          @user.update_column(:treatment, 1 - @treat)
          @treatreg.byeduc[@user.educ] = -1
          @treatreg.save
        end
=end
        
        puts 'treat vector new ' + @treat.to_s
        format.html { 
            redirect_to action: "ndfl", id: @user.id and return }
        format.json { redirect_to action: "ndfl", id: @user.id and return }
      else
#Сюда попадают с недозаполненной формой после нажатия "Отправить"
        puts "Couldn't save user"
        @user.errors.each do |e|
          puts e.to_s
        end
        format.html { 
          puts "rendering new"
          render action: 'new', location: 'user_new'
        }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def tforward (treatment, stage, usrid)
    case stage
    when "askquestions"
      if treatment == 1
        redirect_to action: "showtaxes", id: usrid
      elsif @user.treatment == 0

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/edit.html.erb
<div class="container"> 


<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path

</div>

app/views/users/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Анкеты</div>
  <div class="panel-body">
    <p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th>created</th>
      <th>campaign utm</th>
      <th>source utm</th>
      <th>first user</th>
      <th>treatment</th>
      <th>wage</th>
      <th>range</th>
      <th>taxest</th>
      <th>certainty</th>
      <th>statefin</th>
      <th>m1</th>
      <th>m2</th>
      <th>m3</th>
      <th>m4</th>
      <th>m5</th>
      <th>m6</th>
      <th>m7</th>
      <th>m8</th>
      <th>m9</th>
      <th>educ</th>
      <th>uni</th>
      <th>uniother</th>
      <th>resid</th>
      <th>occup</th>
      <th>elec</th>
      <th>age</th>
      <th>sex</th>
      <th>UserAgent</th>
      <th>treattax</th>
      <th>treatapprove</th>
      <th>petit_account</th>
      <th>petit_spending</th>
      <th>updated</th>
      <th></th>
      <th>HTTPref</th>
      <th>IP</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.created_at %></td>
        <td><%= user.campaign %></td>
        <td><%= user.source %></td>
        <td><%= user.ref %></td>
        <td><%= user.treatment %></td>
        <td><%= number_with_precision( user.aftertaxwage, precision: 0, delimiter: ',') %></td>
        <td><%= number_with_precision( user.wagerange, precision: 0, delimiter: ',') %></td>
        <td><%= user.taxest %></td>
        <td><%= user.taxcertainty %></td>
        <td><%= user.statefin %></td>
        <td><%= user.media1 %></td>
        <td><%= user.media2 %></td>
        <td><%= user.media3 %></td>
        <td><%= user.media4 %></td>
        <td><%= user.media5 %></td>
        <td><%= user.media6 %></td>
        <td><%= user.media7 %></td>
        <td><%= user.media8 %></td>
        <td><%= user.media9 %></td>
        <td><%= user.educ %></td>
        <td><%= user.uni %></td>
        <td><%= user.uniother %></td>
        <td><%= user.residence %></td>
        <td><%= user.occup %></td>
        <td><%= user.elec_presid %></td>
        <td><%= user.age %></td>
        <td><%= user.sex %></td>
        <td><%= user.useragent %></td>
        <td><%= number_with_precision(user.treattax, precision: 0, delimiter: ',') %></td>
        <td><%= number_with_precision(user.treatapprove, precision: 0, delimiter: ',') %></td>
        <td><%= user.petit_account %></td>
        <td><%= user.petit_spending %></td>
        <td><%= user.updated_at %></td>
        <td><%= link_to 'Destroy', user, method: :delete %></td>
        <td><%= user.httpref %></td>
        <td><%= user.ipaddress %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

</div>

app/views/users/ndfl.html.erb
<div class="container"> 

  <div class="jumbotron">
    <h1>Налог на доходы за 2014 год</h1>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading"><h3>Уплаченный вами за год налог на доходы физических лиц</h3></div>
    <div class="panel-body">
      Вы зарабатывали <%= 
      if @user.wagerange > 0
      then number_with_precision(@user.aftertaxwage - @user.wagerange, precision: 0, delimiter: ',') + " - " +  number_with_precision(@user.aftertaxwage + @user.wagerange, precision: 0, delimiter: ',')
      else number_with_precision(@user.aftertaxwage, precision: 0, delimiter: ',')
      end
      %> рублей ежемесячно. <br>
      Вы также ежемесячно выплачивали <b>
      <%= 
      if @user.wagerange > 0
      then number_with_precision((@user.aftertaxwage - @user.wagerange)/0.87*0.13, precision: 0, delimiter: ',') + " - " + number_with_precision((@user.aftertaxwage + @user.wagerange)/0.87*0.13, precision: 0, delimiter: ',')
      else number_with_precision(@user.aftertaxwage/0.87*0.13, precision: 0, delimiter: ',')
      end
      %> рублей</b> налога на доходы (13%). 
      <br><br>
       <%= 
      if @user.wagerange > 0
      then
        'График для средних значений дохода и налога.'
      end
        %>
      <%  library_options = {
        tooltip: {
          isHtml: 'false',
          showColorCode: 'true'
        },
        legend: {
          position: 'bottom'
        },
        chartArea: {
          top: '0'
        }
      }
      data = [
      {
        name: "Зарплата после уплаты налогов", 
        data: [["Учет НДФЛ", @user.aftertaxwage]]
      },
      {
        name: "Налог на доходы физ. лиц", 
        data: [["Учет НДФЛ", number_with_precision(@user.aftertaxwage/0.87*0.13, precision: 0, delimiter: '')]]
      }
    ]
      %>
      
      <%= bar_chart data, {stacked: true, library: library_options, colors: ["00cc8d","d61294"]} %> 
      <br><br>
      <% if @user.treatment == 1 %>
        <%= link_to "Сколько всего вы заплатили налогов", askquestions_user_path(@user), class: "btn btn-lg btn-success" %>
      <% else %>
        <%= link_to "Сколько всего вы заплатили налогов", showtaxes_user_path(@user), class: "btn btn-lg btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/share.html.erb
<div class="container"> 
  <div class="jumbotron">
    <h1>Спасибо за использование нашего сервиса</h1>
  </div>
  
  <div class="panel panel-success">
    <div class="panel-heading">Ваша сводка</div>
    <div class="panel-body">
      <%= link_to 'Уплаченные налоги', showtaxes_user_path(@user) %><br>
      <%= link_to 'Использование налогов', showspending_user_path(@user) %>
      
    </div>
  </div>
  
  <div class="panel panel-primary">
    <div class="panel-heading">Поделитесь ссылкой на ресурс</div>
    <div class="panel-body">
      <div class="fb-share-button" data-lang="ru" data-href="<%=root_url(:subdomain => true)+ "?source="+@user.id.to_s %>" data-layout="button"></div>
      <a class="twitter-share-button" data-lang="ru" href="https://twitter.com/share" data-url="<%=root_url(:subdomain => true)+ "?source="+@user.id.to_s %>">Tweet</a>
      <br>
      <p>Скопируйте ссылку:</p>
      <input type="text" size = "100" value = "<%=root_url(:subdomain => true)+ "?source="+@user.id.to_s %>">
    </div>
  </div>
  <!--
  <div class="panel panel-default">
    <div class="panel-heading">Ваши данные</div>
    <div class="panel-body">

      <label>Средняя зарплата в месяц после налогов в 2014 году: <%= number_with_precision(@user.aftertaxwage, precision: 0, delimiter: ',') %> р.</label>
      <br>
      <label>Работаю в регионе: <%=
      case @user.residence
          when '77' 
            'Москва'
          when '78' 
            'Санкт-Петербург'
          when '1' 
            'Республика Адыгея'
          when '4' 
            'Республика Алтай'
          when '2' 
            'Республика Башкортостан'
          when '3' 
            'Республика Бурятия'
          when '5' 
            'Республика Дагестан'
          when '6' 
            'Республика Ингушетия'
          when '7' 
            'Кабардино-Балкарская республика'
          when '8' 
            'Республика Калмыкия'
          when '9 
           ' 
            'Карачаево-Черкесская республика'
          when '10 
           ' 
            'Республика Карелия'
          when '11 
           ' 
            'Республика Коми'
          when '91' 
            'Республика Крым'
          when '12' 
            'Республика Марий Эл'
          when '13' 
            'Республика Мордовия'
          when '14' 
            'Республика Саха (Якутия)'
          when '15' 
            'Республика Северная Осетия — Алания'
          when '16' 
            'Республика Татарстан'
          when '17' 
            'Республика Тыва'
          when '18' 
            'Удмуртская республика'
          when '19' 
            'Республика Хакасия'
          when '20' 
            'Чеченская республика'
          when '21' 
            'Чувашская республика'
          when '22' 
            'Алтайский край'
          when '75' 
            'Забайкальский край'
          when '41' 
            'Камчатский край'
          when '23' 
            'Краснодарский край'
          when '24' 
            'Красноярский край'
          when '59' 
            'Пермский край'
          when '25' 
            'Приморский край'
          when '26' 
            'Ставропольский край'
          when '27' 
            'Хабаровский край'
          when '28' 
            'Амурская область'
          when '29' 
            'Архангельская область'
          when '30' 
            'Астраханская область'
          when '31' 
            'Белгородская область'
          when '32' 
            'Брянская область'
          when '33' 
            'Владимирская область'
          when '34' 
            'Волгоградская область'
          when '35' 
            'Вологодская область'
          when '36' 
            'Воронежская область'
          when '37' 
            'Ивановская область'
          when '38' 
            'Иркутская область'
          when '39' 
            'Калининградская область'
          when '40' 
            'Калужская область'
          when '42' 
            'Кемеровская область'
          when '43' 
            'Кировская область'
          when '44' 
            'Костромская область'
          when '45' 
            'Курганская область'
          when '46' 
            'Курская область'
          when '47' 
            'Ленинградская область'
          when '48' 
            'Липецкая область'
          when '49' 
            'Магаданская область'
          when '50' 
            'Московская область'
          when '51' 
            'Мурманская область'
          when '52' 
            'Нижегородская область'
          when '53' 
            'Новгородская область'
          when '54' 
            'Новосибирская область'
          when '55' 
            'Омская область'
          when '56' 
            'Оренбургская область'
          when '57' 
            'Орловская область'
          when '58' 
            'Пензенская область'
          when '60' 
            'Псковская область'
          when '61' 
            'Ростовская область'
          when '62' 
            'Рязанская область'
          when '63' 
            'Самарская область'
          when '64' 
            'Саратовская область'
          when '65' 
            'Сахалинская область'
          when '66' 
            'Свердловская область'
          when '67' 
            'Смоленская область'
          when '68' 
            'Тамбовская область'
          when '69' 
            'Тверская область'
          when '70' 
            'Томская область'
          when '71' 
            'Тульская область'
          when '72' 
            'Тюменская область'
          when '73' 
            'Ульяновская область'
          when '74' 
            'Челябинская область'
          when '76' 
            'Ярославская область'
          when '92' 
            'Севастополь'
          when '79' 
            'Еврейская автономная область'
          when '83' 
            'Ненецкий автономный округ'
          when '86' 
            'Ханты-Мансийский автономный округ - Югра'
          when '87' 
            'Чукотский автономный округ'
          when '89' 
            'Ямало-Ненецкий автономный округ'
        else 'Не указан'
        end %>
      </label>
    <br>
    <label>Возраст: <%= @user.age %> лет</label>
      
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">Ваши налоги</div>
    <div class="panel-body">
    </div>
  </div>
  
  
  <div class="panel panel-default">
    <div class="panel-heading">Использование ваших налогов</div>
    <div class="panel-body">
    </div>
  </div>
  -->
  <%= link_to "Посчитать налоги для другого человека", anotheruser_user_path(@user), class: "btn btn-lg btn-success" %>
</div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=369278826474307&version=v2.3";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script>
window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return t;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
</script>
  